### ISSUE TITLE
Results page resizing

### ISSUE THREAD

**Issue by The-Schwiz** [Sophack/firstGroupProject#4]
when resizing page to shrink, search bar moves off page:

![Screenshot 2022-11-16 at 3 22 57 PM](https://user-images.githubusercontent.com/113313870/202286517-852546be-2560-40b0-9d69-e48e3eb0814c.png)

**Comment by Sophack** [comment]
Looks like this issue is fixed as well, however it does overlap the "heart" icon. I was not able to find it in the code so hopefully someone else can fix it or I will figure it out when I attempt the heart modal
![issue0](https://user-images.githubusercontent.com/114966651/202328942-1e80a344-8b5b-4b11-89b9-fd0442bc75ce.jpg)
